use DataBase 20373171
--INSERT INT0 STUDENT(SN0,SNAME,SSEX,SBIRTHDAY,CLASS)VALUES(123,'范彧，'男’，2001-11-04,200231);
SELECT学号=SNO,姓名=SNAE,性别=SSEX,生日=SBIRTHDAY,班级=CLASS
    FROM STUDENT
    ORDER BY SNO DESC
SELECT学号=SNO,姓名=SNAE,班级=CLASS
    FROM STUDENT
    WHERE SNAME LIKE
    ORDER BY CLASS ASC,SNO DESC
SELECT学号=SNO,姓名=SNAME,性别=SSEX,生日=SBIRTHDAY,班级=CLASS
    FROM STUDENT
    WHERE SSEX='男'AND SNO>105ORDER BY SNO ASC
SELECT课程数=COUNT(*)
    FROM COURSE
SELECT课程编号=COURSE.CNO,课程名称=CNAME,平均分=AVG(DEGREE)
    FROM COURSE,SCORE
    WHERE COURSE.CNO=SCORE.CNO
    GROUP BY COURSE.CNO,CNAMEORDER BY AVG (DEGREE)DESC
SELECT学号=STUDENT.SNO,姓名=SNAME,班级=CLASS,平均分=AVG(DEGREE
    FROM SCORE,STUDENT
    WHERE STUDENT.SNO-SCORE.SNO
    GROUP BY STUDENT.SNO,SNAME,CLASS
    HAVING AVG (DEGREE)>80 AND AVG (DEGREE)<=100ORDER BY AVG (DEGREE)DESC